'use client'

import { useState } from 'react'
import * as Icons from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { ScrollArea } from '@/components/ui/scroll-area'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { PageHeader, SectionCard } from './_shared'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'

const platforms = [
  { id: 'instagram', label: 'Instagram', icon: Icons.Instagram, color: 'text-pink-500' },
  { id: 'tiktok', label: 'TikTok', icon: Icons.Music, color: 'text-foreground' },
  { id: 'facebook', label: 'Facebook', icon: Icons.Facebook, color: 'text-blue-600' },
  { id: 'whatsapp', label: 'WhatsApp', icon: Icons.MessageCircle, color: 'text-success' },
]

const languages = ['Manglish', 'Bahasa Malaysia', 'English', 'Rojak']
const tones = ['Excited', 'Friendly', 'Professional', 'Funny', 'Urgent', 'Luxurious']
const contentTypes = [
  { id: 'caption', label: 'Caption', icon: Icons.Type },
  { id: 'hashtags', label: 'Hashtags', icon: Icons.Hash },
  { id: 'script', label: 'Script', icon: Icons.FileText },
  { id: 'hook', label: 'Hook', icon: Icons.Zap },
]

const recentGenerations = [
  { id: 'r1', title: 'Safi Balqis Sunblock Caption', type: 'Caption', platform: 'Instagram', time: '5m ago' },
  { id: 'r2', title: 'RGB Mechanical Keyboard Hook', type: 'Hook', platform: 'TikTok', time: '1h ago' },
  { id: 'r3', title: 'Tudung Bawal Premium Script', type: 'Script', platform: 'TikTok', time: '3h ago' },
  { id: 'r4', title: 'Portable Blender Hashtags', type: 'Hashtags', platform: 'Instagram', time: '5h ago' },
  { id: 'r5', title: 'Wardah Lipstick Caption', type: 'Caption', platform: 'Facebook', time: '1d ago' },
  { id: 'r6', title: 'Anker Power Bank Hook', type: 'Hook', platform: 'WhatsApp', time: '2d ago' },
]

const examples = [
  {
    id: 'ex1',
    type: 'Hook',
    platform: 'TikTok',
    title: 'Manglish Hook Generator',
    sample: 'Eh wait — you all using normal keyboard ah? 😱 This RGB one confirm make your setup level up giler! Tap in lor 👇',
    accent: 'shopee',
  },
  {
    id: 'ex2',
    type: 'Caption',
    platform: 'Instagram',
    title: 'Halal Beauty Caption',
    sample: 'Halal makeup that actually lasts all day? 🌸 Wardah Matte Lipstick confirm your Raya must-have lah. Swipe for shade demo →',
    accent: 'hermes',
  },
  {
    id: 'ex3',
    type: 'Script',
    platform: 'TikTok',
    title: 'Unboxing Script (30s)',
    sample: 'POV: Your blender arrived 😍 (1s) Quick unboxing… (5s) Wah solid build! (10s) Demo smoothie recipe (20s) CTA: link in bio 🔥 (30s)',
    accent: 'success',
  },
]

export function AiContentPage() {
  const [topic, setTopic] = useState('')
  const [tone, setTone] = useState('Excited')
  const [platform, setPlatform] = useState('instagram')
  const [language, setLanguage] = useState('Manglish')
  const [contentType, setContentType] = useState('caption')
  const [result, setResult] = useState('')
  const [loading, setLoading] = useState(false)

  const generate = async () => {
    if (!topic.trim()) {
      toast.error('Type something for HERMES to work with lah!')
      return
    }
    setLoading(true)
    setResult('')
    // Simulate AI generation with realistic content
    await new Promise((r) => setTimeout(r, 1100))
    setResult(buildSample())
    setLoading(false)
    toast.success('Content generated by HERMES AI ✨')
  }

  const buildSample = () => {
    const samples: Record<string, string> = {
      caption: `🚨 ${topic.toUpperCase()} — YOU NEED THIS LAH! 🚨\n\nWah seriously game changer can. ${tone === 'Excited' ? 'I CAN-NOT stop raving about this one!' : tone === 'Urgent' ? 'Stock running out fast, grab now!' : 'Highly recommend for daily use.'}\n\n✨ Why this one:\n• Quality confirm tip-top\n• Price? Best deal in Malaysia now\n• Free shipping sampai rumah\n\n👉 Click link in bio, don't say I never share ah! 🔥\n\n#ShopeeMY #${topic.split(' ').slice(0, 2).join('')} #AffiliateMalaysia #${language === 'Manglish' ? 'ManglishVibes' : 'BestBuy'}`,
      hashtags: `#${topic.split(' ').join('')} #ShopeeMY #ShopeeAffiliateMY #${platform === 'tiktok' ? 'TikTokMadeMeBuyIt' : 'IGShop'} #MalaysiaShopping #BestDealMY #KakiBeli #OnlineShoppingMY #CantikMurah #ReviewMalaysia #WorthIt #${tone === 'Urgent' ? 'LimitedStock' : 'MustHave'} #TrendingNow`,
      script: `[HOOK — 0-3s]\n"Eh wait! You all still using old ${topic}? 😱 Stop right there lor."\n\n[PROBLEM — 3-10s]\nShow frustration with current setup. B-roll of struggles.\n\n[SOLUTION — 10-20s]\nReveal ${topic}. Quick demo of best features. ${tone === 'Excited' ? 'REACT BIG!' : 'Calm walkthrough.'}\n\n[CTA — 20-30s]\n"Link in bio — confirm best price today only! 🔥 Tap now before sold out."\n\n[${language} | ${tone} tone | 30s]`,
      hook: `🤯 "${topic} changed my life — and I'm not even kidding lah."\n\nor\n\n😱 "Nobody told me ${topic} could do THIS..."\n\nor\n\n🔥 "POV: You finally found the ${topic} of your dreams"\n\nor\n\n💀 "Stop scrolling if you haven't tried ${topic} yet..."`,
    }
    return samples[contentType] || samples.caption
  }

  const copyResult = () => {
    navigator.clipboard.writeText(result)
    toast.success('Copied! Paste anywhere lah 😎')
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Content Generator"
        subtitle="HERMES AI writes captions, hooks, scripts & hashtags in Manglish, Bahasa & more."
        icon={Icons.Sparkles}
        accent="hermes"
      >
        <Badge className="bg-hermes-gradient text-white">
          <Icons.Sparkles className="mr-1 size-3" /> AI Powered
        </Badge>
        <Button variant="outline" size="sm" onClick={() => toast.info('Opening template library…')}>
          <Icons.LayoutGrid className="mr-1 size-4" /> Templates
        </Button>
      </PageHeader>

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        {/* Main studio */}
        <div className="space-y-6">
          <Card className="border-hermes/30 bg-gradient-to-br from-hermes/[0.04] to-transparent">
            <div className="border-b p-4">
              <div className="flex items-center gap-2">
                <div className="flex size-8 items-center justify-center rounded-lg bg-hermes-gradient text-white">
                  <Icons.Sparkles className="size-4" />
                </div>
                <div>
                  <h3 className="text-sm font-semibold">Content Generation Studio</h3>
                  <p className="text-xs text-muted-foreground">Tell HERMES what you want to promote</p>
                </div>
              </div>
            </div>
            <CardContent className="space-y-4 p-4">
              {/* Topic input */}
              <div className="space-y-1.5">
                <Label htmlFor="topic" className="text-xs">Topic / Product</Label>
                <Textarea
                  id="topic"
                  placeholder="e.g., Safi Balqis UV Sunblock SPF50 — perfect for Malaysian weather, halal certified, no white cast"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  className="min-h-[80px] resize-none"
                />
              </div>

              {/* Content type */}
              <div className="space-y-2">
                <Label className="text-xs">Content Type</Label>
                <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                  {contentTypes.map((ct) => {
                    const Icon = ct.icon
                    const active = contentType === ct.id
                    return (
                      <button
                        key={ct.id}
                        onClick={() => setContentType(ct.id)}
                        className={cn(
                          'flex flex-col items-center gap-1 rounded-lg border-2 p-2.5 transition-all',
                          active ? 'border-hermes bg-hermes/5 text-hermes' : 'border-border hover:border-hermes/40'
                        )}
                      >
                        <Icon className="size-4" />
                        <span className="text-xs font-medium">{ct.label}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              {/* Platform */}
              <div className="space-y-2">
                <Label className="text-xs">Platform</Label>
                <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                  {platforms.map((p) => {
                    const Icon = p.icon
                    const active = platform === p.id
                    return (
                      <button
                        key={p.id}
                        onClick={() => setPlatform(p.id)}
                        className={cn(
                          'flex items-center justify-center gap-1.5 rounded-lg border-2 p-2 transition-all',
                          active ? 'border-hermes bg-hermes/5' : 'border-border hover:border-hermes/40'
                        )}
                      >
                        <Icon className={cn('size-4', active && p.color)} />
                        <span className="text-xs font-medium">{p.label}</span>
                      </button>
                    )
                  })}
                </div>
              </div>

              {/* Tone + Language */}
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <Label className="text-xs">Tone</Label>
                  <Select value={tone} onValueChange={setTone}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {tones.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">Language</Label>
                  <Select value={language} onValueChange={setLanguage}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {languages.map((l) => <SelectItem key={l} value={l}>{l}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <Button onClick={generate} disabled={loading} className="w-full bg-hermes-gradient hover:opacity-90">
                {loading ? (
                  <><Icons.Loader2 className="mr-1.5 size-4 animate-spin" /> HERMES is thinking…</>
                ) : (
                  <><Icons.Sparkles className="mr-1.5 size-4" /> Generate with AI</>
                )}
              </Button>
            </CardContent>
          </Card>

          {/* Result panel */}
          <Card className="border-border/60">
            <div className="flex items-center justify-between border-b p-4">
              <div className="flex items-center gap-2">
                <Icons.FileText className="size-4 text-hermes" />
                <div>
                  <h3 className="text-sm font-semibold">Generated Result</h3>
                  <p className="text-xs text-muted-foreground">Your AI-crafted {contentType}</p>
                </div>
              </div>
              {result && (
                <div className="flex gap-1.5">
                  <Button variant="outline" size="sm" onClick={copyResult}>
                    <Icons.Copy className="mr-1 size-3.5" /> Copy
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => toast.success('Saved to library!')}>
                    <Icons.Bookmark className="mr-1 size-3.5" /> Save
                  </Button>
                </div>
              )}
            </div>
            <CardContent className="p-4">
              {loading ? (
                <div className="flex h-64 flex-col items-center justify-center">
                  <div className="relative">
                    <div className="flex size-16 items-center justify-center rounded-2xl bg-hermes-gradient text-white">
                      <Icons.Sparkles className="size-8 animate-pulse" />
                    </div>
                    <div className="pulse-ring absolute inset-0 rounded-2xl text-hermes/60" />
                  </div>
                  <p className="mt-4 text-sm font-medium text-hermes">HERMES is crafting your {contentType}…</p>
                  <p className="text-xs text-muted-foreground">Mixing Manglish + {tone} tone + {language}</p>
                </div>
              ) : result ? (
                <div className="space-y-3">
                  <div className="flex flex-wrap gap-1.5">
                    <Badge variant="outline" className="text-[10px] bg-hermes/5 text-hermes">{contentType}</Badge>
                    <Badge variant="outline" className="text-[10px]">{platforms.find(p => p.id === platform)?.label}</Badge>
                    <Badge variant="outline" className="text-[10px]">{tone}</Badge>
                    <Badge variant="outline" className="text-[10px]">{language}</Badge>
                  </div>
                  <pre className="whitespace-pre-wrap rounded-lg bg-muted/50 p-4 text-sm leading-relaxed font-sans">
                    {result}
                  </pre>
                  <div className="flex items-center justify-between rounded-lg bg-hermes/5 p-3 text-xs">
                    <span className="text-muted-foreground">
                      {result.length} chars · ~{Math.ceil(result.split(' ').length / 130)}s read · HERMES v2.1
                    </span>
                    <Badge className="bg-success/15 text-success">
                      <Icons.Check className="mr-1 size-3" /> Ready to post
                    </Badge>
                  </div>
                </div>
              ) : (
                <div className="flex h-64 flex-col items-center justify-center text-center">
                  <Icons.Sparkles className="size-12 text-hermes/30" />
                  <p className="mt-3 text-sm font-medium text-muted-foreground">Ready when you are</p>
                  <p className="text-xs text-muted-foreground">Fill in the form above and let HERMES do the magic ✨</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Example cards */}
          <div>
            <div className="mb-3 flex items-center gap-2">
              <Icons.Lightbulb className="size-4 text-warning" />
              <h3 className="text-sm font-semibold">Example outputs</h3>
              <span className="text-xs text-muted-foreground">— see what HERMES can generate</span>
            </div>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {examples.map((ex) => (
                <Card key={ex.id} className="border-border/60 transition-all hover:-translate-y-0.5 hover:shadow-md">
                  <CardContent className="p-4">
                    <div className="mb-2 flex items-center justify-between">
                      <Badge variant="outline" className={cn('text-[10px]', ex.accent === 'hermes' && 'bg-hermes/5 text-hermes', ex.accent === 'shopee' && 'bg-shopee/5 text-shopee', ex.accent === 'success' && 'bg-success/5 text-success')}>
                        {ex.type}
                      </Badge>
                      <span className="text-[10px] text-muted-foreground">{ex.platform}</span>
                    </div>
                    <p className="text-xs font-semibold">{ex.title}</p>
                    <p className="mt-2 line-clamp-4 text-xs text-muted-foreground">{ex.sample}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </div>

        {/* Recent Generations sidebar */}
        <div className="space-y-4">
          <SectionCard
            title="Recent Generations"
            description="Your past AI outputs"
            icon={Icons.History}
          >
            <ScrollArea className="max-h-[520px]">
              <div className="space-y-1.5">
                {recentGenerations.map((g) => (
                  <button
                    key={g.id}
                    onClick={() => toast.info(`Loading "${g.title}"…`)}
                    className="flex w-full items-start gap-2.5 rounded-lg p-2 text-left transition-colors hover:bg-accent/50"
                  >
                    <div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-hermes/10 text-hermes">
                      <Icons.Sparkles className="size-3.5" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-xs font-medium">{g.title}</p>
                      <div className="mt-0.5 flex items-center gap-1.5 text-[10px] text-muted-foreground">
                        <span>{g.type}</span>
                        <span>·</span>
                        <span>{g.platform}</span>
                        <span>·</span>
                        <span>{g.time}</span>
                      </div>
                    </div>
                  </button>
                ))}
              </div>
            </ScrollArea>
          </SectionCard>

          <Card className="border-hermes/30 bg-gradient-to-br from-hermes/[0.05] to-transparent">
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <div className="flex size-9 items-center justify-center rounded-lg bg-hermes-gradient text-white">
                  <Icons.Bot className="size-5" />
                </div>
                <div>
                  <p className="text-sm font-semibold">HERMES Tip</p>
                  <p className="text-[10px] text-muted-foreground">AI suggestion</p>
                </div>
              </div>
              <p className="mt-3 text-xs text-muted-foreground">
                💡 Add specific details like <span className="font-semibold text-foreground">"SPF50, no white cast, halal"</span> in your topic — HERMES will craft more accurate hooks lah.
              </p>
              <Button size="sm" variant="outline" className="mt-3 w-full" onClick={() => toast.success('Tip applied!')}>
                <Icons.Zap className="mr-1 size-3" /> Try pro tip
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
