'use client'

import { useState } from 'react'
import * as Icons from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { PageHeader, SectionCard } from './_shared'
import { demoProducts } from '@/lib/demo-data'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'

const styles = [
  { id: 'bold', label: 'Bold', desc: 'High contrast, big text', gradient: 'from-shopee to-shopee-dark' },
  { id: 'minimal', label: 'Minimal', desc: 'Clean, lots of space', gradient: 'from-foreground/80 to-foreground' },
  { id: 'vibrant', label: 'Vibrant', desc: 'Colorful, energetic', gradient: 'from-hermes to-shopee' },
  { id: 'halal', label: 'Halal-friendly', desc: 'Soft, modest, pastel', gradient: 'from-success to-warning' },
]

const templates = [
  { id: 'tpl1', name: 'Sale Splash', style: 'Bold', emoji: '🔥', uses: 1240 },
  { id: 'tpl2', name: 'Raya Special', style: 'Halal-friendly', emoji: '🌙', uses: 980 },
  { id: 'tpl3', name: 'Tech Review', style: 'Minimal', emoji: '⚡', uses: 760 },
  { id: 'tpl4', name: 'Beauty Glow', style: 'Vibrant', emoji: '✨', uses: 1820 },
  { id: 'tpl5', name: 'Flash Deal', style: 'Bold', emoji: '⚡', uses: 1450 },
  { id: 'tpl6', name: 'Tudung Elegance', style: 'Halal-friendly', emoji: '🌸', uses: 1120 },
]

interface ThumbOption {
  id: string
  style: string
  headline: string
  subhead: string
  gradient: string
  badge: string
}

export function AiThumbnailsPage() {
  const [product, setProduct] = useState(demoProducts[0].name)
  const [style, setStyle] = useState('bold')
  const [headline, setHeadline] = useState('BEST DEAL TODAY')
  const [subhead, setSubhead] = useState('Limited stock — grab now!')
  const [loading, setLoading] = useState(false)
  const [thumbnails, setThumbnails] = useState<ThumbOption[]>([])
  const [selected, setSelected] = useState<string | null>(null)

  const generate = async () => {
    if (!headline.trim()) {
      toast.error('Type a headline first lah')
      return
    }
    setLoading(true)
    setThumbnails([])
    await new Promise((r) => setTimeout(r, 1300))

    const variants: ThumbOption[] = [
      { id: 'th1', style, headline, subhead, gradient: styles.find((s) => s.id === style)!.gradient, badge: '🔥 Hot' },
      { id: 'th2', style, headline: headline.toUpperCase(), subhead: `${subhead} ⚡`, gradient: 'from-shopee to-warning', badge: '⚡ Flash' },
      { id: 'th3', style, headline, subhead, gradient: 'from-hermes to-hermes-dark', badge: '✨ AI Pick' },
      { id: 'th4', style, headline: `${headline} 🚨`, subhead, gradient: 'from-success to-warning', badge: '🌟 Viral' },
    ]
    setThumbnails(variants)
    setLoading(false)
    toast.success('4 thumbnails generated by HERMES 🎨')
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Thumbnails"
        subtitle="HERMES generates scroll-stopping thumbnails in seconds — pick a style, get 4 options."
        icon={Icons.Image}
        accent="hermes"
      >
        <Badge className="bg-hermes-gradient text-white">
          <Icons.Sparkles className="mr-1 size-3" /> AI Powered
        </Badge>
      </PageHeader>

      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        {/* Left — generator form */}
        <Card className="border-hermes/30 bg-gradient-to-br from-hermes/[0.04] to-transparent">
          <div className="border-b p-4">
            <div className="flex items-center gap-2">
              <div className="flex size-8 items-center justify-center rounded-lg bg-hermes-gradient text-white">
                <Icons.Wand2 className="size-4" />
              </div>
              <div>
                <h3 className="text-sm font-semibold">Thumbnail Generator</h3>
                <p className="text-xs text-muted-foreground">Configure & generate</p>
              </div>
            </div>
          </div>
          <CardContent className="space-y-4 p-4">
            <div className="space-y-1.5">
              <Label className="text-xs">Product</Label>
              <Select value={product} onValueChange={setProduct}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {demoProducts.map((p) => (
                    <SelectItem key={p.id} value={p.name}>{p.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-xs">Style</Label>
              <div className="grid grid-cols-2 gap-2">
                {styles.map((s) => {
                  const active = style === s.id
                  return (
                    <button
                      key={s.id}
                      onClick={() => setStyle(s.id)}
                      className={cn(
                        'overflow-hidden rounded-lg border-2 transition-all',
                        active ? 'border-hermes' : 'border-border hover:border-hermes/40'
                      )}
                    >
                      <div className={cn('h-10 bg-gradient-to-br', s.gradient)} />
                      <div className="p-1.5">
                        <p className="text-[11px] font-semibold">{s.label}</p>
                        <p className="text-[9px] text-muted-foreground">{s.desc}</p>
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="headline" className="text-xs">Headline text</Label>
              <Input id="headline" value={headline} onChange={(e) => setHeadline(e.target.value)} placeholder="e.g., BEST DEAL TODAY" />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="subhead" className="text-xs">Sub-text</Label>
              <Input id="subhead" value={subhead} onChange={(e) => setSubhead(e.target.value)} placeholder="e.g., Limited stock!" />
            </div>

            <Button onClick={generate} disabled={loading} className="w-full bg-hermes-gradient hover:opacity-90">
              {loading ? (
                <><Icons.Loader2 className="mr-1.5 size-4 animate-spin" /> Generating…</>
              ) : (
                <><Icons.Sparkles className="mr-1.5 size-4" /> Generate Thumbnails</>
              )}
            </Button>

            <div className="rounded-lg bg-muted/40 p-2.5 text-xs">
              <p className="flex items-center gap-1 font-medium text-hermes">
                <Icons.Lightbulb className="size-3" /> Pro tip
              </p>
              <p className="mt-0.5 text-muted-foreground">
                Keep headlines under 6 words — they read better on mobile feeds lah.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Right — generated thumbnails */}
        <div className="space-y-6">
          <SectionCard
            title="Generated Thumbnails"
            description="4 variations — pick your favorite"
            icon={Icons.Images}
            action={thumbnails.length > 0 && (
              <Button size="sm" variant="outline" onClick={() => toast.success('All 4 downloaded!')}>
                <Icons.Download className="mr-1 size-3" /> Download all
              </Button>
            )}
          >
            {loading ? (
              <div className="flex h-64 flex-col items-center justify-center">
                <div className="relative">
                  <div className="flex size-16 items-center justify-center rounded-2xl bg-hermes-gradient text-white">
                    <Icons.Image className="size-8 animate-pulse" />
                  </div>
                  <div className="pulse-ring absolute inset-0 rounded-2xl text-hermes/60" />
                </div>
                <p className="mt-4 text-sm font-medium text-hermes">HERMES is designing…</p>
                <p className="text-xs text-muted-foreground">Mixing colors, layouts & typography</p>
              </div>
            ) : thumbnails.length > 0 ? (
              <div className="grid gap-4 sm:grid-cols-2">
                {thumbnails.map((t) => (
                  <Card
                    key={t.id}
                    className={cn(
                      'overflow-hidden border-2 transition-all',
                      selected === t.id ? 'border-hermes shadow-md' : 'border-border/60 hover:border-hermes/40'
                    )}
                  >
                    <div className={cn('relative aspect-video bg-gradient-to-br', t.gradient)}>
                      <div className="absolute inset-0 bg-grid opacity-10" />
                      <div className="absolute inset-0 flex flex-col items-center justify-center p-4 text-center text-white">
                        <Badge className="absolute left-2 top-2 bg-white/20 text-white backdrop-blur text-[10px]">
                          {t.badge}
                        </Badge>
                        <p className="text-2xl font-black tracking-tight drop-shadow-md">{t.headline}</p>
                        <p className="mt-1 text-xs text-white/90">{t.subhead}</p>
                        <div className="mt-2 rounded-full bg-white/20 px-2 py-0.5 text-[10px] backdrop-blur">
                          🛒 Shopee · {product.split(' ').slice(0, 2).join(' ')}
                        </div>
                      </div>
                    </div>
                    <CardContent className="p-3">
                      <div className="flex items-center gap-1.5">
                        <Button size="sm" variant="outline" className="flex-1" onClick={() => toast.success('Downloaded!')}>
                          <Icons.Download className="mr-1 size-3" /> Download
                        </Button>
                        <Button size="sm" variant="outline" onClick={() => toast.info('Opening customizer…')}>
                          <Icons.Settings2 className="size-3" />
                        </Button>
                        <Button
                          size="sm"
                          className={cn('flex-1', selected === t.id ? 'bg-success hover:bg-success' : 'bg-hermes-gradient hover:opacity-90')}
                          onClick={() => {
                            setSelected(t.id)
                            toast.success('Thumbnail selected — ready for posting! ✨')
                          }}
                        >
                          {selected === t.id ? (
                            <><Icons.Check className="mr-1 size-3" /> Selected</>
                          ) : (
                            <><Icons.Check className="mr-1 size-3" /> Use this</>
                          )}
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : (
              <div className="flex h-64 flex-col items-center justify-center text-center">
                <Icons.Image className="size-12 text-hermes/30" />
                <p className="mt-3 text-sm font-medium text-muted-foreground">Your 4 thumbnails will appear here</p>
                <p className="text-xs text-muted-foreground">Configure on the left & hit Generate</p>
              </div>
            )}
          </SectionCard>

          {/* Template gallery */}
          <SectionCard
            title="Template Gallery"
            description="Pre-built layouts — click to use"
            icon={Icons.LayoutGrid}
          >
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
              {templates.map((t) => (
                <button
                  key={t.id}
                  onClick={() => {
                    setStyle(styles.find((s) => s.label === t.style)?.id ?? 'bold')
                    setHeadline(t.name.toUpperCase())
                    toast.success(`Template "${t.name}" loaded`)
                  }}
                  className="group overflow-hidden rounded-lg border-2 border-border/60 text-left transition-all hover:border-hermes/40 hover:shadow-sm"
                >
                  <div className={cn(
                    'flex aspect-square items-center justify-center bg-gradient-to-br text-3xl',
                    styles.find((s) => s.label === t.style)?.gradient
                  )}>
                    <span className="drop-shadow-md">{t.emoji}</span>
                  </div>
                  <div className="p-2">
                    <p className="truncate text-xs font-semibold">{t.name}</p>
                    <p className="text-[9px] text-muted-foreground">{t.uses} affiliates used</p>
                  </div>
                </button>
              ))}
            </div>
          </SectionCard>
        </div>
      </div>
    </div>
  )
}
