'use client'

import { useState } from 'react'
import * as Icons from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { PageHeader, SectionCard } from './_shared'
import { SmartImage } from '@/components/ui/smart-image'
import { demoProducts } from '@/lib/demo-data'
import { cn } from '@/lib/utils'
import { toast } from 'sonner'

const styles = [
  { id: 'bold', label: 'Bold', desc: 'High contrast, big text', gradient: 'from-shopee to-shopee-dark' },
  { id: 'minimal', label: 'Minimal', desc: 'Clean, lots of space', gradient: 'from-foreground/80 to-foreground' },
  { id: 'vibrant', label: 'Vibrant', desc: 'Colorful, energetic', gradient: 'from-hermes to-shopee' },
  { id: 'halal', label: 'Halal-friendly', desc: 'Soft, modest, pastel', gradient: 'from-success to-warning' },
]

const templates = [
  { id: 'tpl1', name: 'Sale Splash', style: 'Bold', emoji: '🔥', uses: 1240 },
  { id: 'tpl2', name: 'Raya Special', style: 'Halal-friendly', emoji: '🌙', uses: 980 },
  { id: 'tpl3', name: 'Tech Review', style: 'Minimal', emoji: '⚡', uses: 760 },
  { id: 'tpl4', name: 'Beauty Glow', style: 'Vibrant', emoji: '✨', uses: 1820 },
  { id: 'tpl5', name: 'Flash Deal', style: 'Bold', emoji: '⚡', uses: 1450 },
  { id: 'tpl6', name: 'Tudung Elegance', style: 'Halal-friendly', emoji: '🌸', uses: 1120 },
]

interface GeneratedThumb {
  id: string
  image: string
  prompt: string
  badge: string
  variationLabel: string
}

const placeholderVariations = [
  { id: 'ph1', gradient: 'from-hermes to-hermes-dark', badge: '🎨 Soon' },
  { id: 'ph2', gradient: 'from-success to-warning', badge: '🚀 Soon' },
]

export function AiThumbnailsPage() {
  const [product, setProduct] = useState(demoProducts[0].name)
  const [style, setStyle] = useState('bold')
  const [headline, setHeadline] = useState('BEST DEAL TODAY')
  const [subhead, setSubhead] = useState('Limited stock — grab now!')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [thumbnails, setThumbnails] = useState<GeneratedThumb[]>([])
  const [selected, setSelected] = useState<string | null>(null)

  const styleLabel = styles.find((s) => s.id === style)?.label ?? 'Bold'

  const generate = async () => {
    if (!headline.trim()) {
      toast.error('Type a headline first lah')
      return
    }
    setLoading(true)
    setError(null)
    setThumbnails([])
    setSelected(null)

    // Two parallel variations — different text overlays for variety.
    // API handles prompt construction; we just vary the textOverlay field.
    const variations = [
      {
        id: 'th1',
        textOverlay: headline,
        badge: '🔥 Variation 1',
        variationLabel: `${styleLabel} · Headline focus`,
      },
      {
        id: 'th2',
        textOverlay: `${headline} — ${subhead}`,
        badge: '✨ Variation 2',
        variationLabel: `${styleLabel} · Full text`,
      },
    ]

    try {
      const results = await Promise.allSettled(
        variations.map(async (v) => {
          const res = await fetch('/api/ai/thumbnails', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              productName: product,
              style: styleLabel,
              textOverlay: v.textOverlay,
            }),
          })
          const data = await res.json().catch(() => ({}))
          if (!res.ok) {
            throw new Error(data?.error || `Generation failed (${res.status})`)
          }
          if (!data.image) {
            throw new Error('No image returned by HERMES')
          }
          return {
            id: v.id,
            image: data.image as string,
            prompt: (data.prompt as string) || '',
            badge: v.badge,
            variationLabel: v.variationLabel,
          } as GeneratedThumb
        })
      )

      const successful = results
        .filter((r): r is PromiseFulfilledResult<GeneratedThumb> => r.status === 'fulfilled')
        .map((r) => r.value)

      if (successful.length === 0) {
        setError('AI image generation is warming up. Please try again in a moment.')
        toast.error('Generation failed — please try again')
      } else {
        setThumbnails(successful)
        if (successful.length === 1) {
          toast.success('1 thumbnail generated by HERMES 🎨')
        } else {
          toast.success(`${successful.length} thumbnails generated by HERMES 🎨`)
        }
      }
    } catch (err) {
      console.error('Thumbnail generation error:', err)
      setError('AI image generation is warming up. Please try again in a moment.')
      toast.error('Something went wrong — please try again')
    } finally {
      setLoading(false)
    }
  }

  const downloadImage = (image: string, idx: number) => {
    try {
      const slug = product
        .split(' ')
        .slice(0, 2)
        .join('-')
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, '')
      const link = document.createElement('a')
      link.href = image
      link.download = `hermes-thumbnail-${slug || 'product'}-${idx + 1}.png`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      toast.success('Thumbnail downloaded! 📥')
    } catch {
      toast.error('Download failed — try right-clicking the image')
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="AI Thumbnails"
        subtitle="HERMES generates scroll-stopping thumbnails in seconds — pick a style, get real AI-designed options."
        icon={Icons.Image}
        accent="hermes"
      >
        <Badge className="bg-hermes-gradient text-white">
          <Icons.Sparkles className="mr-1 size-3" /> AI Powered
        </Badge>
      </PageHeader>

      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        {/* Left — generator form */}
        <Card className="border-hermes/30 bg-gradient-to-br from-hermes/[0.04] to-transparent">
          <div className="border-b p-4">
            <div className="flex items-center gap-2">
              <div className="flex size-8 items-center justify-center rounded-lg bg-hermes-gradient text-white">
                <Icons.Wand2 className="size-4" />
              </div>
              <div>
                <h3 className="text-sm font-semibold">Thumbnail Generator</h3>
                <p className="text-xs text-muted-foreground">Configure &amp; generate</p>
              </div>
            </div>
          </div>
          <CardContent className="space-y-4 p-4">
            <div className="space-y-1.5">
              <Label className="text-xs">Product</Label>
              <Select value={product} onValueChange={setProduct}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {demoProducts.map((p) => (
                    <SelectItem key={p.id} value={p.name}>{p.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-xs">Style</Label>
              <div className="grid grid-cols-2 gap-2">
                {styles.map((s) => {
                  const active = style === s.id
                  return (
                    <button
                      key={s.id}
                      onClick={() => setStyle(s.id)}
                      className={cn(
                        'overflow-hidden rounded-lg border-2 transition-all',
                        active ? 'border-hermes' : 'border-border hover:border-hermes/40'
                      )}
                    >
                      <div className={cn('h-10 bg-gradient-to-br', s.gradient)} />
                      <div className="p-1.5">
                        <p className="text-[11px] font-semibold">{s.label}</p>
                        <p className="text-[9px] text-muted-foreground">{s.desc}</p>
                      </div>
                    </button>
                  )
                })}
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="headline" className="text-xs">Headline text</Label>
              <Input id="headline" value={headline} onChange={(e) => setHeadline(e.target.value)} placeholder="e.g., BEST DEAL TODAY" />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="subhead" className="text-xs">Sub-text</Label>
              <Input id="subhead" value={subhead} onChange={(e) => setSubhead(e.target.value)} placeholder="e.g., Limited stock!" />
            </div>

            <Button onClick={generate} disabled={loading} className="w-full bg-hermes-gradient hover:opacity-90">
              {loading ? (
                <><Icons.Loader2 className="mr-1.5 size-4 animate-spin" /> Generating…</>
              ) : (
                <><Icons.Sparkles className="mr-1.5 size-4" /> Generate Thumbnails</>
              )}
            </Button>

            <div className="rounded-lg bg-muted/40 p-2.5 text-xs">
              <p className="flex items-center gap-1 font-medium text-hermes">
                <Icons.Lightbulb className="size-3" /> Pro tip
              </p>
              <p className="mt-0.5 text-muted-foreground">
                AI generation takes 5–15 seconds. Keep headlines under 6 words — they read better on mobile feeds lah.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Right — generated thumbnails */}
        <div className="space-y-6">
          <SectionCard
            title="Generated Thumbnails"
            description="Real AI variations — pick your favorite"
            icon={Icons.Images}
            action={thumbnails.length > 0 && !loading && (
              <Button size="sm" variant="outline" onClick={generate}>
                <Icons.RefreshCw className="mr-1 size-3" /> Generate Again
              </Button>
            )}
          >
            {loading ? (
              <div className="space-y-4">
                {/* Live status banner */}
                <div className="flex items-center gap-3 rounded-lg border border-hermes/20 bg-hermes/[0.04] p-3">
                  <div className="flex size-10 items-center justify-center rounded-xl bg-hermes-gradient text-white">
                    <Icons.Loader2 className="size-5 animate-spin" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-hermes">
                      HERMES is generating your thumbnails…
                    </p>
                    <p className="truncate text-xs text-muted-foreground">
                      This usually takes 5–15 seconds. Designing colors, layouts &amp; typography for {product}.
                    </p>
                  </div>
                  <div className="hidden items-center gap-1 text-[10px] font-medium text-hermes/70 sm:flex">
                    <Icons.Sparkles className="size-3" />
                    <span>AI working</span>
                  </div>
                </div>

                {/* Skeleton shimmer grid */}
                <div className="grid gap-4 sm:grid-cols-2">
                  {[0, 1, 2, 3].map((i) => (
                    <Card key={i} className="overflow-hidden border-border/60">
                      <div className="relative aspect-square overflow-hidden bg-muted">
                        <div className="absolute inset-0 bg-gradient-to-br from-hermes/10 via-hermes/5 to-shopee/10" />
                        <div className="shimmer absolute inset-0" />
                        <div className="absolute inset-0 flex items-center justify-center">
                          <Icons.Image className="size-8 text-hermes/30" />
                        </div>
                        <Badge className="absolute left-2 top-2 bg-hermes/20 text-hermes backdrop-blur text-[10px]">
                          <Icons.Sparkles className="mr-1 size-2.5" /> Designing…
                        </Badge>
                      </div>
                      <CardContent className="p-3">
                        <div className="mb-2 h-3 w-2/3 rounded bg-muted animate-pulse" />
                        <div className="flex gap-1.5">
                          <div className="h-7 flex-1 rounded-md bg-muted animate-pulse" />
                          <div className="h-7 w-7 rounded-md bg-muted animate-pulse" />
                          <div className="h-7 flex-1 rounded-md bg-muted animate-pulse" />
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            ) : error ? (
              <div className="flex h-64 flex-col items-center justify-center text-center">
                <div className="flex size-14 items-center justify-center rounded-2xl bg-warning/10 text-warning">
                  <Icons.AlertTriangle className="size-7" />
                </div>
                <p className="mt-4 text-sm font-semibold text-foreground">
                  AI image generation is warming up
                </p>
                <p className="mt-1 max-w-sm text-xs text-muted-foreground">{error}</p>
                <Button
                  onClick={generate}
                  variant="outline"
                  className="mt-4 border-hermes/40 text-hermes hover:bg-hermes/10"
                >
                  <Icons.RefreshCw className="mr-1.5 size-3.5" /> Retry generation
                </Button>
              </div>
            ) : thumbnails.length > 0 ? (
              <div className="grid gap-4 sm:grid-cols-2">
                {thumbnails.map((t, idx) => (
                  <Card
                    key={t.id}
                    className={cn(
                      'overflow-hidden border-2 transition-all',
                      selected === t.id ? 'border-hermes shadow-md' : 'border-border/60 hover:border-hermes/40'
                    )}
                  >
                    <div className="relative aspect-square bg-muted">
                      <SmartImage
                        src={t.image}
                        alt={`AI-generated thumbnail for ${product} — ${t.variationLabel}`}
                        width={1024}
                        height={1024}
                        priority={idx === 0}
                        className="size-full object-cover"
                      />
                      <Badge className="absolute left-2 top-2 bg-hermes/90 text-white backdrop-blur text-[10px]">
                        {t.badge}
                      </Badge>
                      {selected === t.id && (
                        <div className="absolute right-2 top-2 flex size-6 items-center justify-center rounded-full bg-success text-white shadow">
                          <Icons.Check className="size-3.5" />
                        </div>
                      )}
                    </div>
                    <CardContent className="space-y-2 p-3">
                      <p className="truncate text-[11px] text-muted-foreground">{t.variationLabel}</p>
                      <div className="flex items-center gap-1.5">
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1"
                          onClick={() => downloadImage(t.image, idx)}
                        >
                          <Icons.Download className="mr-1 size-3" /> Download
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => toast.info('Customization coming soon')}
                          aria-label="Customize thumbnail"
                        >
                          <Icons.Settings2 className="size-3" />
                        </Button>
                        <Button
                          size="sm"
                          className={cn(
                            'flex-1',
                            selected === t.id ? 'bg-success hover:bg-success' : 'bg-hermes-gradient hover:opacity-90'
                          )}
                          onClick={() => {
                            setSelected(t.id)
                            toast.success('Thumbnail selected! ✨')
                          }}
                        >
                          {selected === t.id ? (
                            <><Icons.Check className="mr-1 size-3" /> Selected</>
                          ) : (
                            <><Icons.Check className="mr-1 size-3" /> Use This</>
                          )}
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}

                {/* Placeholder cards for upcoming variations */}
                {placeholderVariations.map((p) => (
                  <Card
                    key={p.id}
                    className="overflow-hidden border-2 border-dashed border-border/60"
                  >
                    <div className={cn('relative flex aspect-square items-center justify-center bg-gradient-to-br', p.gradient)}>
                      <div className="absolute inset-0 bg-grid opacity-10" />
                      <div className="relative flex flex-col items-center text-center text-white">
                        <Icons.Clock className="size-8 opacity-80" />
                        <p className="mt-2 text-sm font-bold drop-shadow">Variation coming soon</p>
                        <p className="text-[10px] text-white/80">More AI styles landing soon</p>
                      </div>
                      <Badge className="absolute left-2 top-2 bg-white/20 text-white backdrop-blur text-[10px]">
                        {p.badge}
                      </Badge>
                    </div>
                    <CardContent className="p-3">
                      <p className="text-[11px] text-muted-foreground">HERMES is learning new styles…</p>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : (
              <div className="flex h-64 flex-col items-center justify-center text-center">
                <Icons.Image className="size-12 text-hermes/30" />
                <p className="mt-3 text-sm font-medium text-muted-foreground">
                  Your AI thumbnails will appear here
                </p>
                <p className="text-xs text-muted-foreground">
                  Configure on the left &amp; hit Generate
                </p>
              </div>
            )}
          </SectionCard>

          {/* Template gallery */}
          <SectionCard
            title="Template Gallery"
            description="Pre-built layouts — click to use"
            icon={Icons.LayoutGrid}
          >
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
              {templates.map((t) => (
                <button
                  key={t.id}
                  onClick={() => {
                    setStyle(styles.find((s) => s.label === t.style)?.id ?? 'bold')
                    setHeadline(t.name.toUpperCase())
                    toast.success(`Template "${t.name}" loaded`)
                  }}
                  className="group overflow-hidden rounded-lg border-2 border-border/60 text-left transition-all hover:border-hermes/40 hover:shadow-sm"
                >
                  <div className={cn(
                    'flex aspect-square items-center justify-center bg-gradient-to-br text-3xl',
                    styles.find((s) => s.label === t.style)?.gradient
                  )}>
                    <span className="drop-shadow-md">{t.emoji}</span>
                  </div>
                  <div className="p-2">
                    <p className="truncate text-xs font-semibold">{t.name}</p>
                    <p className="text-[9px] text-muted-foreground">{t.uses} affiliates used</p>
                  </div>
                </button>
              ))}
            </div>
          </SectionCard>
        </div>
      </div>
    </div>
  )
}
